# Generated by Django 4.0.2 on 2022-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_mobile', models.CharField(max_length=12)),
                ('customer_address', models.TextField()),
            ],
        ),
    ]
